name: Feature Request
description: Suggest a feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you would like.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this feature would solve or the workflow it would improve.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision the feature working.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you have considered.
    validations:
      required: false
