use super::SmartPrompt;

/// Helper to reduce boilerplate when defining built-in prompts.
fn p(
    name: &str,
    description: &str,
    template: &str,
    category: &str,
    tags: &[&str],
) -> SmartPrompt {
    SmartPrompt {
        name: name.into(),
        description: description.into(),
        template: template.into(),
        category: category.into(),
        tags: tags.iter().map(|s| (*s).into()).collect(),
    }
}

/// Return the comprehensive set of built-in SmartPrompts shipped with Nerve.
pub fn builtin_prompts() -> Vec<SmartPrompt> {
    vec![
        // ── Writing (12) ────────────────────────────────────────────────────
        p(
            "Summarize",
            "Create a clear, concise summary of any text",
            "Provide a clear, concise summary of the following text. Focus on the key points and main ideas. Keep the summary to about one-third of the original length.\n\n{{input}}",
            "Writing",
            &["summary", "shorten", "digest"],
        ),
        p(
            "Expand",
            "Expand text with more detail and supporting points",
            "Expand the following text with additional detail, examples, and supporting points. Maintain the original tone and style while making the content richer and more comprehensive.\n\n{{input}}",
            "Writing",
            &["expand", "elaborate", "lengthen"],
        ),
        p(
            "Rewrite Formally",
            "Rewrite text in a formal, professional tone",
            "Rewrite the following text in a formal, professional tone suitable for business or academic contexts. Preserve the original meaning while elevating the register and removing any colloquialisms.\n\n{{input}}",
            "Writing",
            &["formal", "professional", "tone"],
        ),
        p(
            "Rewrite Casually",
            "Rewrite text in a casual, conversational tone",
            "Rewrite the following text in a casual, friendly, and conversational tone. Make it feel approachable and easy to read while keeping the core message intact.\n\n{{input}}",
            "Writing",
            &["casual", "informal", "conversational"],
        ),
        p(
            "Fix Grammar",
            "Correct grammar, spelling, and punctuation errors",
            "Carefully proofread the following text and fix all grammar, spelling, and punctuation errors. Only make corrections \u{2014} do not change the style, tone, or meaning. List each change you made at the end.\n\n{{input}}",
            "Writing",
            &["grammar", "spelling", "proofread"],
        ),
        p(
            "Improve Clarity",
            "Improve the clarity and readability of text",
            "Improve the clarity and readability of the following text. Simplify complex sentences, remove unnecessary jargon, improve logical flow, and ensure the message is easy to understand. Preserve the original meaning.\n\n{{input}}",
            "Writing",
            &["clarity", "readability", "simplify"],
        ),
        p(
            "Write Email Reply",
            "Draft a professional reply to an email",
            "Draft a professional, courteous reply to the following email. Match an appropriate tone (formal for business, friendly for colleagues). Keep it concise and actionable. If the email asks questions, address each one.\n\n{{input}}",
            "Writing",
            &["email", "reply", "professional"],
        ),
        p(
            "Create Outline",
            "Generate a structured outline for any topic",
            "Create a well-structured outline for the following topic or text. Use a hierarchical format with main sections, subsections, and key points. Include enough detail to serve as a writing guide.\n\n{{input}}",
            "Writing",
            &["outline", "structure", "plan"],
        ),
        p(
            "Generate Headlines",
            "Create multiple compelling headline options",
            "Generate 10 compelling headline options for the following content. Include a mix of styles: informative, curiosity-driven, how-to, and listicle formats. Each headline should be concise and attention-grabbing.\n\n{{input}}",
            "Writing",
            &["headlines", "titles", "copywriting"],
        ),
        p(
            "Proofread",
            "Thorough proofreading with tracked changes",
            "Perform a thorough proofread of the following text. Check for:\n- Spelling and typographical errors\n- Grammar and syntax issues\n- Punctuation mistakes\n- Inconsistent formatting or style\n- Awkward phrasing\n\nProvide the corrected text followed by a numbered list of every change made with a brief explanation.\n\n{{input}}",
            "Writing",
            &["proofread", "edit", "review"],
        ),
        p(
            "Simplify Language",
            "Rewrite text using simpler, more accessible language",
            "Rewrite the following text using simpler, more accessible language. Target a general audience with no specialized knowledge. Replace jargon with plain alternatives and break up long sentences.\n\n{{input}}",
            "Writing",
            &["simplify", "plain language", "accessible"],
        ),
        p(
            "Change Tone",
            "Rewrite text in a specified tone",
            "Rewrite the following text in the tone specified. If no tone is specified, rewrite it in a neutral, balanced tone. Preserve the factual content and key message.\n\nDesired tone: {{tone}}\n\nText:\n{{input}}",
            "Writing",
            &["tone", "rewrite", "style"],
        ),

        // ── Coding (12) ────────────────────────────────────────────────────
        p(
            "Explain Code",
            "Get a clear, step-by-step explanation of code",
            "Explain the following code in clear, step-by-step terms. Cover:\n1. The overall purpose of the code\n2. How each major section works\n3. Any important algorithms or patterns used\n4. The inputs and outputs\n\nUse plain language suitable for an intermediate developer.\n\n```\n{{input}}\n```",
            "Coding",
            &["explain", "understand", "walkthrough"],
        ),
        p(
            "Fix Bug",
            "Identify and fix bugs in code",
            "Analyze the following code and identify any bugs, logic errors, or potential issues. For each problem found:\n1. Describe the bug and why it occurs\n2. Explain the impact (crash, wrong output, etc.)\n3. Provide the corrected code\n4. Explain the fix\n\n```\n{{input}}\n```",
            "Coding",
            &["debug", "fix", "bug"],
        ),
        p(
            "Refactor",
            "Refactor code for better design and readability",
            "Refactor the following code to improve its design, readability, and maintainability. Apply relevant best practices such as:\n- Single Responsibility Principle\n- DRY (Don't Repeat Yourself)\n- Meaningful variable and function names\n- Proper error handling\n- Reduced complexity\n\nProvide the refactored code and explain each change.\n\n```\n{{input}}\n```",
            "Coding",
            &["refactor", "clean code", "design"],
        ),
        p(
            "Add Comments",
            "Add clear documentation comments to code",
            "Add clear, useful documentation comments to the following code. Include:\n- Module/file-level documentation explaining the purpose\n- Function/method doc comments with parameter and return descriptions\n- Inline comments for non-obvious logic\n- Any relevant usage examples\n\nFollow the language's standard documentation conventions.\n\n```\n{{input}}\n```",
            "Coding",
            &["comments", "documentation", "docstring"],
        ),
        p(
            "Write Tests",
            "Generate comprehensive unit tests for code",
            "Write comprehensive unit tests for the following code. Include:\n- Happy path tests for normal operation\n- Edge case tests (empty inputs, boundary values, etc.)\n- Error case tests (invalid inputs, failure modes)\n- Use descriptive test names that explain the scenario\n\nUse the appropriate testing framework for the language.\n\n```\n{{input}}\n```",
            "Coding",
            &["tests", "unit test", "testing"],
        ),
        p(
            "Convert Language",
            "Convert code from one programming language to another",
            "Convert the following code to {{target_language}}. Produce idiomatic code in the target language \u{2014} don't just do a literal translation. Use the target language's conventions, standard library, and best practices. Note any features that don't have a direct equivalent.\n\nTarget language: {{target_language}}\n\n```\n{{input}}\n```",
            "Coding",
            &["convert", "translate", "port"],
        ),
        p(
            "Optimize Performance",
            "Optimize code for better performance",
            "Analyze the following code for performance issues and optimize it. Consider:\n- Time complexity improvements\n- Memory usage optimization\n- Unnecessary allocations or copies\n- Better data structures or algorithms\n- Caching opportunities\n\nProvide the optimized code and explain each improvement with its expected impact.\n\n```\n{{input}}\n```",
            "Coding",
            &["optimize", "performance", "speed"],
        ),
        p(
            "Code Review",
            "Perform a thorough code review",
            "Perform a thorough code review of the following code. Evaluate:\n- Correctness: Are there any bugs or logic errors?\n- Design: Is the code well-structured and maintainable?\n- Performance: Are there any inefficiencies?\n- Security: Are there any vulnerabilities?\n- Readability: Is the code clear and well-documented?\n- Best practices: Does it follow language conventions?\n\nProvide specific, actionable feedback with severity ratings (critical/major/minor/suggestion).\n\n```\n{{input}}\n```",
            "Coding",
            &["review", "feedback", "quality"],
        ),
        p(
            "Generate Docs",
            "Generate API or module documentation",
            "Generate comprehensive documentation for the following code. Include:\n- Overview and purpose\n- Public API reference with types, parameters, and return values\n- Usage examples for each public function/method\n- Any important notes about error handling or edge cases\n\nFormat the documentation in Markdown.\n\n```\n{{input}}\n```",
            "Coding",
            &["docs", "documentation", "api"],
        ),
        p(
            "Explain Error",
            "Explain an error message and how to fix it",
            "Explain the following error message in plain language. Cover:\n1. What the error means\n2. Common causes of this error\n3. Step-by-step instructions to fix it\n4. How to prevent it in the future\n\nIf code context is provided, give a specific fix for that context.\n\n{{input}}",
            "Coding",
            &["error", "debug", "troubleshoot"],
        ),
        p(
            "Write Function",
            "Generate a function from a description",
            "Write a function based on the following description. Include:\n- Clear function signature with typed parameters and return value\n- Input validation\n- Proper error handling\n- Documentation comments\n- At least two usage examples\n\nDescription:\n{{input}}",
            "Coding",
            &["generate", "function", "implement"],
        ),
        p(
            "Regex Help",
            "Create or explain regular expressions",
            "Help with the following regular expression task. If a regex is provided, explain it in detail. If a description is provided, write the regex.\n\nFor explanations, break down each part of the pattern. For new regexes, provide:\n- The regex pattern\n- An explanation of each component\n- Example matches and non-matches\n- Any caveats or limitations\n\n{{input}}",
            "Coding",
            &["regex", "pattern", "match"],
        ),

        // ── Translation (8) ────────────────────────────────────────────────
        p(
            "Translate to English",
            "Translate text into English",
            "Translate the following text into natural, fluent English. Preserve the original meaning, tone, and nuance as closely as possible. If any phrases are culturally specific, provide a brief explanation in parentheses.\n\n{{input}}",
            "Translation",
            &["english", "translate"],
        ),
        p(
            "Translate to Spanish",
            "Translate text into Spanish",
            "Translate the following text into natural, fluent Spanish. Use standard Latin American Spanish unless otherwise specified. Preserve the original meaning, tone, and nuance.\n\n{{input}}",
            "Translation",
            &["spanish", "translate"],
        ),
        p(
            "Translate to French",
            "Translate text into French",
            "Translate the following text into natural, fluent French. Preserve the original meaning, tone, and nuance. Use standard metropolitan French.\n\n{{input}}",
            "Translation",
            &["french", "translate"],
        ),
        p(
            "Translate to German",
            "Translate text into German",
            "Translate the following text into natural, fluent German. Preserve the original meaning, tone, and nuance. Use standard High German (Hochdeutsch).\n\n{{input}}",
            "Translation",
            &["german", "translate"],
        ),
        p(
            "Translate to Japanese",
            "Translate text into Japanese",
            "Translate the following text into natural Japanese. Use an appropriate level of formality based on context (default to polite/desu-masu form). Include furigana for uncommon kanji in parentheses.\n\n{{input}}",
            "Translation",
            &["japanese", "translate"],
        ),
        p(
            "Translate to Arabic",
            "Translate text into Arabic",
            "Translate the following text into natural, fluent Modern Standard Arabic. Preserve the original meaning, tone, and nuance.\n\n{{input}}",
            "Translation",
            &["arabic", "translate"],
        ),
        p(
            "Translate to Chinese",
            "Translate text into Simplified Chinese",
            "Translate the following text into natural, fluent Simplified Chinese (Mandarin). Preserve the original meaning, tone, and nuance.\n\n{{input}}",
            "Translation",
            &["chinese", "mandarin", "translate"],
        ),
        p(
            "Translate to Portuguese",
            "Translate text into Portuguese",
            "Translate the following text into natural, fluent Brazilian Portuguese. Preserve the original meaning, tone, and nuance.\n\n{{input}}",
            "Translation",
            &["portuguese", "translate"],
        ),

        // ── Analysis (10) ───────────────────────────────────────────────────
        p(
            "Analyze Sentiment",
            "Analyze the sentiment and emotional tone of text",
            "Analyze the sentiment and emotional tone of the following text. Provide:\n1. Overall sentiment (positive, negative, neutral, mixed)\n2. Confidence level (high, medium, low)\n3. Key emotional tones detected (e.g., joy, frustration, urgency)\n4. Specific phrases that indicate the sentiment\n5. A brief summary of the emotional landscape\n\n{{input}}",
            "Analysis",
            &["sentiment", "emotion", "tone"],
        ),
        p(
            "Extract Key Points",
            "Extract the main points and takeaways from text",
            "Extract the key points and main takeaways from the following text. Present them as:\n1. A numbered list of main points (in order of importance)\n2. Supporting details for each point\n3. A one-sentence overall takeaway\n\nBe thorough but concise \u{2014} capture everything important without adding interpretation.\n\n{{input}}",
            "Analysis",
            &["key points", "extract", "takeaways"],
        ),
        p(
            "Compare & Contrast",
            "Compare and contrast two or more items",
            "Provide a detailed comparison of the following items. Structure your analysis as:\n1. Overview of each item\n2. Similarities\n3. Differences (organized by category)\n4. Strengths and weaknesses of each\n5. Recommendation or conclusion (if applicable)\n\nUse a balanced, objective perspective.\n\n{{input}}",
            "Analysis",
            &["compare", "contrast", "versus"],
        ),
        p(
            "SWOT Analysis",
            "Perform a SWOT analysis",
            "Perform a comprehensive SWOT analysis of the following subject. For each quadrant, provide 3\u{2013}5 specific, actionable points:\n\n**Strengths** (internal positive factors)\n**Weaknesses** (internal negative factors)\n**Opportunities** (external positive factors)\n**Threats** (external negative factors)\n\nConclude with strategic recommendations based on the analysis.\n\n{{input}}",
            "Analysis",
            &["swot", "strategy", "business"],
        ),
        p(
            "Fact Check",
            "Verify claims and identify potential inaccuracies",
            "Analyze the following text for factual accuracy. For each claim or statement:\n1. Identify the specific claim\n2. Assess its accuracy (confirmed, likely true, uncertain, likely false, false)\n3. Provide reasoning or known context\n4. Note any claims that need additional verification\n\nBe transparent about the limits of your knowledge and clearly distinguish between verified facts and assessments.\n\n{{input}}",
            "Analysis",
            &["fact check", "verify", "accuracy"],
        ),
        p(
            "Identify Bias",
            "Identify potential biases in text",
            "Analyze the following text for potential biases. Look for:\n1. Loaded or emotionally charged language\n2. One-sided presentation of issues\n3. Omission of relevant perspectives\n4. Generalizations or stereotypes\n5. Selection bias in examples or evidence\n6. Framing effects\n\nProvide specific examples from the text and suggest how it could be made more balanced.\n\n{{input}}",
            "Analysis",
            &["bias", "objectivity", "critical thinking"],
        ),
        p(
            "Root Cause Analysis",
            "Identify the root cause of a problem",
            "Perform a root cause analysis of the following problem. Use the following approach:\n1. Clearly define the problem\n2. Apply the '5 Whys' technique to dig deeper\n3. Identify contributing factors\n4. Determine the root cause(s)\n5. Propose corrective actions\n6. Suggest preventive measures\n\n{{input}}",
            "Analysis",
            &["root cause", "problem solving", "5 whys"],
        ),
        p(
            "Data Interpretation",
            "Interpret data and identify patterns",
            "Analyze and interpret the following data. Provide:\n1. Summary of what the data shows\n2. Key patterns, trends, or anomalies\n3. Statistical observations (if applicable)\n4. Possible explanations for the patterns\n5. Limitations of the data\n6. Recommendations for further analysis\n\n{{input}}",
            "Analysis",
            &["data", "statistics", "patterns"],
        ),
        p(
            "Explain Concept",
            "Explain a concept clearly and thoroughly",
            "Explain the following concept in clear, accessible terms. Structure your explanation as:\n1. Simple one-sentence definition\n2. Detailed explanation with context\n3. A real-world analogy or example\n4. Why it matters / practical applications\n5. Common misconceptions\n6. Related concepts to explore\n\n{{input}}",
            "Analysis",
            &["explain", "concept", "learn"],
        ),
        p(
            "Pros and Cons",
            "List the pros and cons of something",
            "Provide a balanced, thorough list of pros and cons for the following. For each point:\n- Be specific, not generic\n- Explain the reasoning\n- Rate the significance (high/medium/low)\n\nEnd with an overall assessment and any caveats that depend on specific circumstances.\n\n{{input}}",
            "Analysis",
            &["pros", "cons", "advantages", "disadvantages"],
        ),

        // ── Creative (9) ────────────────────────────────────────────────────
        p(
            "Brainstorm Ideas",
            "Generate creative ideas for any topic",
            "Brainstorm a diverse set of creative ideas for the following topic. Generate at least 10 ideas ranging from conventional to unconventional. For each idea:\n- Give it a catchy title\n- Provide a 1\u{2013}2 sentence description\n- Rate its feasibility (easy/medium/hard)\n\nDon't self-censor \u{2014} include ambitious and unconventional ideas alongside practical ones.\n\n{{input}}",
            "Creative",
            &["brainstorm", "ideas", "creative"],
        ),
        p(
            "Write Story",
            "Create a short story or narrative",
            "Write a compelling short story based on the following prompt or theme. Include:\n- Vivid characters with distinct voices\n- A clear narrative arc (setup, conflict, resolution)\n- Sensory details and engaging prose\n- Dialogue where appropriate\n\nAim for approximately 500\u{2013}800 words unless otherwise specified.\n\n{{input}}",
            "Creative",
            &["story", "fiction", "narrative"],
        ),
        p(
            "Create Metaphor",
            "Generate metaphors and analogies for concepts",
            "Create a set of vivid, illuminating metaphors and analogies for the following concept. Provide:\n1. 3\u{2013}5 metaphors or analogies, each from a different domain (nature, technology, everyday life, etc.)\n2. A brief explanation of how each metaphor maps to the concept\n3. Which metaphor works best for different audiences\n\nMake them memorable and easy to understand.\n\n{{input}}",
            "Creative",
            &["metaphor", "analogy", "figurative"],
        ),
        p(
            "Generate Names",
            "Generate creative name ideas",
            "Generate creative name ideas for the following. Provide:\n- 15\u{2013}20 name suggestions organized by style (professional, playful, abstract, descriptive, etc.)\n- A brief note on the feeling each name evokes\n- Domain/trademark considerations (if applicable)\n- Your top 3 recommendations with reasoning\n\n{{input}}",
            "Creative",
            &["names", "naming", "branding"],
        ),
        p(
            "Write Poem",
            "Compose a poem on any topic",
            "Write a poem based on the following theme or subject. Create something with:\n- Vivid imagery and sensory language\n- A consistent rhythm or structure\n- Emotional resonance\n- Original metaphors\n\nFeel free to choose the form (free verse, sonnet, haiku, etc.) that best fits the subject, or specify a preferred form.\n\n{{input}}",
            "Creative",
            &["poem", "poetry", "verse"],
        ),
        p(
            "Create Slogan",
            "Craft catchy slogans and taglines",
            "Create 10 catchy slogans or taglines for the following. Each should be:\n- Memorable and concise (under 10 words)\n- Emotionally resonant\n- Easy to say aloud\n- Unique and not a cliche\n\nInclude a mix of styles: witty, inspiring, direct, and playful. Mark your top 3 picks.\n\n{{input}}",
            "Creative",
            &["slogan", "tagline", "marketing"],
        ),
        p(
            "Role Play",
            "Engage in a role-play scenario",
            "Let's engage in a role-play scenario. I'll describe the situation and the role I'd like you to play. Stay in character throughout, responding as that person or entity would. Be authentic to the character's knowledge, personality, and communication style.\n\nScenario:\n{{input}}",
            "Creative",
            &["roleplay", "character", "simulation"],
        ),
        p(
            "Devil's Advocate",
            "Argue the opposing perspective",
            "Play devil's advocate for the following position or idea. Construct the strongest possible counter-arguments by:\n1. Identifying the weakest assumptions in the position\n2. Presenting evidence or reasoning that challenges each point\n3. Offering alternative explanations or viewpoints\n4. Highlighting potential unintended consequences\n\nBe rigorous and fair \u{2014} the goal is to stress-test the idea, not to be contrarian.\n\n{{input}}",
            "Creative",
            &["devil's advocate", "counter", "debate"],
        ),
        p(
            "Rewrite Creatively",
            "Rewrite text with creative flair",
            "Rewrite the following text with creative flair and engaging style. Inject personality, vivid language, and a compelling rhythm while preserving the core message. Make it a pleasure to read.\n\n{{input}}",
            "Creative",
            &["creative writing", "style", "flair"],
        ),

        // ── Productivity (10) ──────────────────────────────────────────────
        p(
            "Create Action Items",
            "Extract actionable tasks from text",
            "Extract clear, specific action items from the following text. For each action item:\n- Write it as a concrete, actionable task (start with a verb)\n- Assign a priority (high/medium/low)\n- Note any deadlines mentioned\n- Identify the responsible party (if mentioned)\n\nOrganize by priority and group related items together.\n\n{{input}}",
            "Productivity",
            &["action items", "tasks", "todo"],
        ),
        p(
            "Meeting Summary",
            "Summarize meeting notes or transcripts",
            "Create a structured meeting summary from the following notes or transcript. Include:\n\n**Attendees:** (if mentioned)\n**Date:** (if mentioned)\n**Key Discussion Points:** (numbered list)\n**Decisions Made:** (numbered list)\n**Action Items:** (with owners and deadlines)\n**Open Questions:** (items needing follow-up)\n**Next Steps:** (what happens next)\n\n{{input}}",
            "Productivity",
            &["meeting", "summary", "notes"],
        ),
        p(
            "Decision Matrix",
            "Create a structured decision matrix",
            "Create a decision matrix to help evaluate the following options. Steps:\n1. Identify the key criteria for the decision\n2. Weight each criterion by importance (1\u{2013}5)\n3. Score each option against each criterion (1\u{2013}5)\n4. Calculate weighted scores\n5. Present results in a clear table\n6. Provide a recommendation with reasoning\n\n{{input}}",
            "Productivity",
            &["decision", "matrix", "evaluate"],
        ),
        p(
            "Prioritize Tasks",
            "Prioritize a list of tasks using proven frameworks",
            "Prioritize the following tasks using the Eisenhower Matrix (urgent/important framework). Categorize each task into:\n\n1. **Do First** (urgent + important)\n2. **Schedule** (important, not urgent)\n3. **Delegate** (urgent, not important)\n4. **Eliminate** (neither urgent nor important)\n\nProvide reasoning for each categorization and suggest an execution order.\n\n{{input}}",
            "Productivity",
            &["prioritize", "eisenhower", "tasks"],
        ),
        p(
            "Write Report",
            "Draft a professional report",
            "Draft a professional report based on the following information. Use this structure:\n\n1. **Executive Summary** (1 paragraph)\n2. **Background/Context**\n3. **Findings/Analysis** (main body)\n4. **Conclusions**\n5. **Recommendations**\n\nUse clear, professional language and support claims with the provided data.\n\n{{input}}",
            "Productivity",
            &["report", "professional", "business"],
        ),
        p(
            "Create Agenda",
            "Create a structured meeting agenda",
            "Create a well-structured meeting agenda based on the following topics and goals. Include:\n- Meeting title and objective\n- Time allocations for each item\n- Discussion leader for each topic (if applicable)\n- Required preparation or pre-reads\n- Space for Q&A and wrap-up\n\nTotal meeting time: {{duration}} (default: 60 minutes)\n\n{{input}}",
            "Productivity",
            &["agenda", "meeting", "planning"],
        ),
        p(
            "Elevator Pitch",
            "Craft a concise elevator pitch",
            "Craft a compelling elevator pitch for the following. The pitch should:\n- Be deliverable in 30\u{2013}60 seconds\n- Hook the listener in the first sentence\n- Clearly state the value proposition\n- Address the target audience's pain point\n- End with a call to action\n\nProvide three versions: formal, conversational, and bold.\n\n{{input}}",
            "Productivity",
            &["pitch", "elevator", "persuade"],
        ),
        p(
            "Project Brief",
            "Create a project brief document",
            "Create a comprehensive project brief based on the following information. Include:\n\n1. **Project Overview** (goals and scope)\n2. **Problem Statement** (what we're solving)\n3. **Target Audience / Stakeholders**\n4. **Success Criteria** (measurable outcomes)\n5. **Key Deliverables**\n6. **Timeline / Milestones**\n7. **Resources Needed**\n8. **Risks and Mitigation**\n9. **Out of Scope** (explicit exclusions)\n\n{{input}}",
            "Productivity",
            &["project", "brief", "planning"],
        ),
        p(
            "Draft Email",
            "Draft a professional email",
            "Draft a professional email based on the following context. Ensure the email:\n- Has a clear, specific subject line\n- Opens with appropriate context\n- States the purpose concisely\n- Includes any necessary details\n- Ends with a clear call to action\n- Uses an appropriate sign-off\n\n{{input}}",
            "Productivity",
            &["email", "professional", "communication"],
        ),
        p(
            "ELI5",
            "Explain like I'm five years old",
            "Explain the following concept as if you were talking to a five-year-old. Use simple words, fun comparisons to everyday things kids understand, and keep it short and engaging. Avoid any technical jargon.\n\n{{input}}",
            "Productivity",
            &["eli5", "simple", "explain"],
        ),
    ]
}
